# Site settings
author: Andrada Lorena Popa
title: 
header-img: img/home-bg.png
email: andrada.lorena.popa@gmail.com
copyright_name: Andrada Lorena Popa
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  andrada1403

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
